### ISSUE TITLE
Pin Clipboard Items for Fast Entry?

### ISSUE THREAD

**Issue by squirrelboot** [tinytacoteam/zazu-clipboard#25]
Zazu combines several tools I use, and I want to keep using it! 

One thing I lack though, is that I cannot pin some common items to the clipboard history which I reference a lot. Is there some plugin/option that can be added to allow me to pin/save selected clipboard items?

**Comment by bayleedev** [comment]
Have you tried zazu-snippets?

https://github.com/tinytacoteam/zazu-snippets
